(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ac-auto-show-menu nil)
 '(ac-auto-start 2)
 '(ac-delay 0.035)
 '(ac-use-menu-map t)
 '(ag-highlight-search t)
 '(anzu-deactivate-region t)
 '(anzu-mode-lighter "")
 '(anzu-search-threshold 1000)
 '(c-basic-offset 4)
 '(case-fold-search t)
 '(coffee-tab-width 2)
 '(css-indent-offset 2)
 '(cua-enable-cua-keys nil)
 '(custom-safe-themes
   (quote
    ("0c311fb22e6197daba9123f43da98f273d2bfaeeaeb653007ad1ee77f0003037" default)))
 '(delete-by-moving-to-trash t)
 '(dired-dwim-target t)
 '(dired-listing-switches "-alh")
 '(dired-recursive-copies (quote always))
 '(ediff-split-window-function (quote split-window-horizontally))
 '(ediff-window-setup-function (quote ediff-setup-windows-plain))
 '(elscreen-display-screen-number nil)
 '(eshell-cmpl-ignore-case t)
 '(eshell-prompt-function (quote my-eshell-prompt))
 '(eshell-prompt-regexp "^[^#$n]*[#>] ")
 '(eshell-scroll-show-maximum-output nil)
 '(flycheck-completion-system (quote ido))
 '(flycheck-phpcs-standard "/Users/l3msh0/repos/walti-wp-plugin/ruleset.xml")
 '(flycheck-phpmd-rulesets (quote ("codesize" "design" "naming" "unusedcode")))
 '(helm-completing-read-handlers-alist
   (quote
    ((find-file)
     (dired-create-directory)
     (dired-do-rename)
     (dired-do-copy)
     (describe-function . helm-completing-read-symbols)
     (describe-variable . helm-completing-read-symbols)
     (debug-on-entry . helm-completing-read-symbols)
     (find-function . helm-completing-read-symbols)
     (trace-function . helm-completing-read-symbols)
     (trace-function-foreground . helm-completing-read-symbols)
     (trace-function-background . helm-completing-read-symbols)
     (find-tag . helm-completing-read-with-cands-in-buffer)
     (ffap-alternate-file)
     (tmm-menubar)
     (helm-ag))))
 '(helm-img-thumbnail-height 200)
 '(helm-migemo-mode t)
 '(highlight-symbol-idle-delay 0.7)
 '(highlight-symbol-on-navigation-p t)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(initial-scratch-message nil)
 '(js-indent-level 2)
 '(linum-format "%4d")
 '(magit-branch-arguments (quote ("--no-track")))
 '(magit-push-always-verify nil)
 '(make-backup-files nil)
 '(markdown-enable-wiki-links t)
 '(migemo-coding-system (quote utf-8-unix))
 '(migemo-command "cmigemo")
 '(migemo-options (quote ("-q" "--emacs")))
 '(ns-command-modifier (quote meta))
 '(omnisharp-server-executable-path "~/repos/OmniSharpServer/OmniSharp/bin/Debug/Omnisharp.exe")
 '(open-junk-file-format "~/Google ドライブ/junk/%Y/%m/%d-%H%M%S." t)
 '(org-return-follows-link t)
 '(org-todo-keywords
   (quote
    ((sequence "TODO(t)" "STARTED(s)" "WAITING(w)" "|" "DONE(x)" "CANCEL(c)"))))
 '(package-selected-packages (quote (undo-tree queue noctilux-theme)))
 '(rspec-use-vagrant-when-possible t)
 '(ruby-insert-encoding-magic-comment nil)
 '(skk-jisyo-edit-user-accepts-editing t)
 '(tab-width 4)
 '(tramp-default-method "rsync")
 '(twittering-convert-fix-size 32)
 '(twittering-default-show-replied-tweets 3)
 '(twittering-status-format "%i %p%s %t %@%R")
 '(twittering-timer-interval 180)
 '(twittering-use-master-password t)
 '(twittering-use-native-retweet t)
 '(web-mode-code-indent-offset 2)
 '(web-mode-css-indent-offset 2)
 '(web-mode-enable-auto-pairing nil)
 '(web-mode-enable-current-element-highlight t)
 '(web-mode-markup-indent-offset 2)
 '(web-mode-script-padding 2)
 '(web-mode-sql-indent-offset 2)
 '(web-mode-style-padding 2)
 '(whitespace-style (quote (face trailing tabs tab-mark)))
 '(yas-prompt-functions
   (quote
    (my/yas-helm-prompt yas-x-prompt yas-dropdown-prompt yas-completing-prompt yas-ido-prompt yas-no-prompt))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(org-level-4 ((t (:inherit outline-4 :foreground "#666699" :weight extra-bold)))))
